// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlertCounts() {
  return window['go']['main']['App']['GetAlertCounts']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRecentAlerts(arg1) {
  return window['go']['main']['App']['GetRecentAlerts'](arg1);
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function ListInterfaces() {
  return window['go']['main']['App']['ListInterfaces']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartCapture(arg1) {
  return window['go']['main']['App']['StartCapture'](arg1);
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}
