// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {store} from '../models';

export function GetAlertCounts():Promise<Record<string, number>>;

export function GetConfig():Promise<config.Config>;

export function GetRecentAlerts(arg1:number):Promise<Array<store.Alert>>;

export function IsRunning():Promise<boolean>;

export function ListInterfaces():Promise<Array<string>>;

export function SaveConfig(arg1:config.Config):Promise<string>;

export function StartCapture(arg1:string):Promise<string>;

export function StopCapture():Promise<void>;
